### ISSUE TITLE
How to successfully implement a megarepo

### ISSUE THREAD

**Issue by jcreamer898** [jcreamer898/blog-post-ideas#1]
Needs to discuss options like Bolt and Lerna.
Talk about the build tooling.

**Comment by kwelch** [comment]
Don't forget the part on how to migrate to one 😜

**Comment by wsmd** [comment]
_\*cries in yarn workspaces\*_

**Comment by kwelch** [comment]
@wsmd we made the transition from workspace to `bolt`. Is there anything in particular holding you back? Under the hood, they are very similar.

**Comment by wsmd** [comment]
> Is there anything in particular holding you back?

@kwelch Only reason holding me back is that yarn workspaces is working very well for me haha. Now your question got me curious, what made you switch from yarn to bolt?

**Comment by kwelch** [comment]
bolt does not allow for workspaces to install a different versions of a singular package. This helps avoid large dependency trees and makes sharing easier since versions of things like react are not going to conflict between the workspaces.

**Comment by jcreamer898** [comment]
DONE
https://www.jonathancreamer.com/how-to-successfully-manage-a-monorepo-aka-megarepo/
